# -*- coding: utf-8 -*-
"""Assesment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcxWQ0PaNKqz8YQpVaHg4Q7GdKpU-gbe

**Python Assesment 1**

1) Import pandas and read in the banklist.csv file into a dataframe called
banks.
"""

import numpy as np
import pandas as pd
banks = pd.read_csv('banklist.csv')
banks

"""2) Show the head of the dataframe"""

banks.head()

"""3) What are the column names?"""

1 Bank Name
2 city
3 ST
4 convert_from_missing_indexer_tuple
5 acquiring_insitutions
6 Closing date
7 Updated date

"""4) How many States (ST) are represented in this data set?

"""

# There are 44 unique states (ST) represented in the dataset.

"""5) Get a list or array of all the states in the data set"""

states_list = banks['ST'].unique()
states_list

"""6) What are the top 5 states with the most failed banks?


"""

state_count = banks['ST'].value_counts()
top_5_states = state_count.head(5)
top_5_states

"""7) What are the top 5 acquiring institutions?"""

acquiring_insitutions = banks['Acquiring Institution'].value_counts()
top_5_acquiring_insitutions = acquiring_insitutions.head(5)
top_5_acquiring_insitutions

"""8) How many banks has the State Bank of Texas acquired? How many of
them were actually in Texas?
"""

state_bank_of_texas = banks[banks['Acquiring Institution'] == 'State Bank of Texas']
banks_acquired_by_state_bank_of_texas = state_bank_of_texas['Bank Name'].nunique()
banks_acquired_by_state_bank_of_texas

"""9) What is the most common city in California for a bank to fail in?"""

city = banks[banks['ST'] == 'CA']
most_common_city = city['City'].value_counts().idxmax()
most_common_city

"""**Python Assesment 2**

Q 1: Develop a Line chart using the functionality of pandas to show how
automobile sales fluctuate from year to year.
"""

import pandas as pd
historical_automobile_sales = pd.read_csv('historical_automobile_sales.csv')